#!/bin/bash

#PBS -l nodes=1:ppn=1,walltime=24:00:00,mem=8000mb
#PBS -N align_05
#PBS -M ats423@nyu.edu
#PBS -m a
#PBS -j oe

cd ${PBS_O_WORKDIR}

module load bwa/gnu/0.7.8

bwa mem -M /scratch/ats423/refence_genome_green/Creinhardtii_236.fa /scratch/ats423/hw4/Sample_lane3-index05-ACAGTG-371/output_forward_paired_05.fq.gz /scratch/ats423/hw4/Sample_lane3-index05-ACAGTG-371/output_reverse_paired_05.fq.gz > /scratch/ats423/hw4/Sample_lane3-index01-ATCACG-634/index_5_PE.sam
