#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=25000mb
#PBS -N STAR_Align_Control_1
#PBS -M ats423@nyu.edu
#PBS -m a
#PBS -j oe

cd ${PBS_O_WORKDIR}

module load star/intel/2.4

STAR --genomeDir /scratch/ats423/hw8/rice_genome --readFilesIn /scratch/ats423/hw8/Bio_Rep_1_Control/ID003_TGACCA_
L006_R1_001.fastq /scratch/ats423/hw8/Bio_Rep_1_Control/ID003_TGACCA_L006_R2_001.fastq --outSAMtype BAM SortedByCo
ordinate --limitBAMsortRAM 20000000000 --runThreadN 8
