#!/bin/bash

#PBS -l nodes=1:ppn=12,walltime=04:00:00,mem=24000mb
#PBS -N velvet
#PBS -M ats423@nyu.edu
#PBS -m a
#PBS -j oe

cd ${PBS_O_WORKDIR}

module load velvet/gnu/kmer92/1.2.10

module load perl/intel/5.18.2

export PATH=$PATH:/scratch/ats423/hw13/VelvetOptimiser-2.2.5

perl /scratch/ats423/hw13/VelvetOptimiser-2.2.5/VelvetOptimiser.pl -s 21 -e 45 -
t 12 -amosfile -o '-cov_cutoff auto' -f '-shortPaired -fastq /scratch/ats423/hw1
3/CR1690_shuffled.fq'
